development: &dev
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: isbaysoft_dev
  pool: 5
  username: root
  password: ruby
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: isbaysoft_test
  pool: 5
  username: root
  password: ruby
  socket: /var/run/mysqld/mysqld.sock


cucumber:
  <<: *test